<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\User;
use App\Models\Backend\Meal;
use App\Models\Backend\RoomBookingHistory;
use Carbon\Carbon;

class AutoGenerateDailyMeals extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'meals:generate-daily';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Auto generate daily meal entries for all active residents unless turned off';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $today = Carbon::today()->format('Y-m-d');
        $this->info("Generating daily meals for date: {$today}");

        // Only get active resident bookings where status = 0 (checked in) and check_in <= today
        $activeBookings = RoomBookingHistory::where('status', 0)
            ->whereDate('check_in', '<=', $today)
            ->get();

        $targetUserIds = collect();

        foreach ($activeBookings as $booking) {
            $user = null;
            if (!empty($booking->phone)) {
                $cleanPhone = preg_replace('/[^0-9]/', '', $booking->phone);
                $cleanPhone10 = strlen($cleanPhone) >= 6 ? (strlen($cleanPhone) > 10 ? substr($cleanPhone, -10) : $cleanPhone) : '';
                if ($cleanPhone10) {
                    $user = User::whereRaw("REPLACE(REPLACE(REPLACE(phone, ' ', ''), '-', ''), '+', '') LIKE ?", ["%{$cleanPhone10}%"])->first();
                }
            }
            if (!$user && !empty($booking->email)) {
                $user = User::where('email', $booking->email)->first();
            }

            if ($user) {
                $targetUserIds->push($user->id);
            }
        }

        $targetUserIds = $targetUserIds->unique();
        $mealService = app(\App\Services\MealService::class);

        $count = 0;
        foreach ($targetUserIds as $userId) {
            $depositInfo = $mealService->getUserMealDepositBalance($userId);
            $isZeroDeposit = $depositInfo['is_zero_deposit'];
            $existing = Meal::where('user_id', $userId)->whereDate('date', $today)->first();

            if (!$existing) {
                if ($isZeroDeposit) {
                    Meal::create([
                        'user_id'   => $userId,
                        'date'      => $today,
                        'half_meal' => 0,
                        'full_meal' => 0,
                        'is_off'    => 1,
                        'made_by'   => 1, // System / Admin
                        'note'      => 'Auto Meal OFF (Zero Deposit)',
                    ]);
                } else {
                    Meal::create([
                        'user_id'   => $userId,
                        'date'      => $today,
                        'half_meal' => 0,
                        'full_meal' => 1,
                        'is_off'    => 0,
                        'made_by'   => 1, // System / Admin
                        'note'      => 'Auto generated daily meal',
                    ]);
                }
                $count++;
            } else {
                if ($isZeroDeposit && str_contains($existing->note ?? '', 'Auto')) {
                    $existing->update([
                        'half_meal' => 0,
                        'full_meal' => 0,
                        'is_off'    => 1,
                        'note'      => 'Auto Meal OFF (Zero Deposit)',
                    ]);
                } elseif (!$isZeroDeposit && $existing->is_off && $existing->note === 'Auto Meal OFF (Zero Deposit)') {
                    $existing->update([
                        'half_meal' => 0,
                        'full_meal' => 1,
                        'is_off'    => 0,
                        'note'      => 'Auto generated daily meal',
                    ]);
                }
            }
        }

        $this->info("Auto-generated meals for {$count} users.");
        return 0;
    }
}
